name: new test
on: 
  pull_request:
    types:
      - closed
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - dev
      - 'feature/**'
      - 'dev-*'
    paths-ignore:
      - 'readme'
env:
  HERO_OF_HEROES: AVI-BHAI
jobs:
  test:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Cache node module
        id: cache-node-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: install dependencies
        if: steps.cache-node-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: lint
        run: npm run lint
      - name: run tests
        #continue-on-error: true
        run: npm test
      - name: envrionment variable
        run: echo ${{secrets.HERO_NO_1}} echo ${{secrets.BHAI_BHAI}}

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs: 
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Cache node module
        id: cache-node-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: install dependencies
        if: steps.cache-node-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: create-build
        run: npm run build
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
      - name: collect-filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}'>> $GITHUB_OUTPUT ';'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: global-var-print
        run: echo ${{env.HERO_OF_HEROES}} 
      - name: download-dist-files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Display structure of downloaded files
        run: ls
      - name: print-publish-file
        run: echo "${{needs.build.outputs.script-file}}"
      - name: deploy
        run: echo "deploying...."
  report:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: report
        #if: ${{ failure() }} 
        run: echo ${{toJSON(github)}}
      
